### ISSUE TITLE
Issues with rigs that were converted to Rigify

### ISSUE THREAD

**Issue by VP1989** [Jetpack-Crow/autogrip#10]
I have imported a model from Koikatsu to Blender and converted the bones to Rigify. When I try to use this add-on, it keeps giving me the same error.

```
~~~~~~~~~~~START~~~~~~~~~~~~

skeleton is RIG-Armature.003
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\autogrip-main\handrig.py", line 698, in find_hand_root
    return obj.pose.bones['DEF-hand.L']
KeyError: 'bpy_prop_collection[key]: key "DEF-hand.L" not found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\autogrip-main\handrig.py", line 747, in execute
    righthandroot = find_hand_root('R')
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\autogrip-main\handrig.py", line 711, in find_hand_root
    raise RuntimeError("Couldn't find hand root. Are you sure you have the right rig type?")
RuntimeError: Couldn't find hand root. Are you sure you have the right rig type?
Error: Python: Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\autogrip-main\handrig.py", line 698, in find_hand_root
    return obj.pose.bones['DEF-hand.L']
KeyError: 'bpy_prop_collection[key]: key "DEF-hand.L" not found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\autogrip-main\handrig.py", line 747, in execute
    righthandroot = find_hand_root('R')
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\autogrip-main\handrig.py", line 711, in find_hand_root
    raise RuntimeError("Couldn't find hand root. Are you sure you have the right rig type?")
RuntimeError: Couldn't find hand root. Are you sure you have the right rig type?
```

Clicking on "Guess Rig Type" brings me the same message: "Rig doesn't match precoded types."

Please let me know what other info I should provide to solve this.

**Comment by Jetpack-Crow** [comment]
This add-on works based off of the names of bones. I've never worked with that model type and don't know what to expect from its rigs, but if you don't have a bone called DEF-hand.L, that must mean the conversion isn't updating the deformation bones' names to match Rigify's defaults, only adding additional controllers on top of them. I've been thinking of adding more tools to work with custom types of rigs for a while, but haven't figured out a decent way to implement them yet. You could try renaming the original rig's bones to match Rigify's bone names more closely, but otherwise, this may be outside the scope of this add-on for right now.
